### ISSUE TITLE
Unable to connect to MariaDB in host machine

### ISSUE THREAD

**Issue by boonpingsg** [xlrl/docker-mantisbt#16]
Hi there,

I have been trying to configure the mantis on my host machine running DSM 7.0.1. The MariaDB is installed on the host machine. But I cannot seem to get the mantis to configure. I keep getting bad database connection. May I ask do you have a solution to this issue?

Thanks,
BP

**Comment by XelaRellum** [comment]
You have to make sure you can access the host mysql from within the container. To get this you need to configure mysql to listen to the host ip address. This should be not that difficult but of course it opens security holes since then you can connect to the mysql database from within your local network if you firewall isnt configured to block this.

The solution in our company is to run the maria database inside a container as well, will within a docker-compose configuration.
If you need to access the database from other applications on your host you can configure the mariadb container to expose to 127.0.0.1:
```yaml
ports:
      - "127.0.0.1:3306:3306"
```

**Comment by XelaRellum** [comment]
No more response, closing this issue for now.
