### ISSUE TITLE
Image doesn't work with SQL Server Database

### ISSUE THREAD

**Issue by natanielcz** [xlrl/docker-mantisbt#6]
Hi,

Thanks for creating this image! I've tested it and it works great but my customer expects it to work with SQL Server. 

I tried to connect to SQL Server database from the container with this image but I receive this error:

![image](https://user-images.githubusercontent.com/1231703/76012494-aaf00f80-5f16-11ea-8b27-ab2d26e866a0.png)

We should include in the image SQL Server driver and PHP extension for SQL Server. I try to do it on my own and push a PR to your repo but I'm not a PHP guy so I may have some troubles with this PHP extension.

**Comment by XelaRellum** [comment]
Feel free to clone this repository and modify the `Dockerfile`. You can test this by building it using docker. The command you might be locking at `docker-php-ext-install`.

If you run into difficulties working on this feel free to ask for advice.

**Comment by natanielcz** [comment]
I've prepared the required changes. Please take a look and publish It to docker registry ASAP :) I'd like to use the image from the public docker registry :smile:

**Comment by XelaRellum** [comment]
Thanks for the pull request. Unfortunately, the MS SQL driver is not just a package to be installed, but a MS download with EULAs and all attached. So I am not going to accept the commit request, since this would add non open-source code to the image.

But feel free to add your fork of this repository to the docker hub. It's free and easy and just what I have done when I was starting out with this image. I will happily put a link to your repo and docker image to this project's README

**Comment by natanielcz** [comment]
I'll do that. I'll reach You in this issue with the link to my Docker image ;)

**Comment by XelaRellum** [comment]
Perfect! Thanks for your understanding.

**Comment by XelaRellum** [comment]
So I am closing this issue. Will be adding the link to you Docker image / Github page as soon as you are ready.
